name: Linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git remote -v
    - name: Fetch branches
      run: |
        git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        git fetch --unshallow
    - run: git branch -avv
    - run: git log --oneline --graph --decorate -20
    - run: ./bootstrap
    - run: ./configure
    - run: make test-all
