name: linux/mac

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [gcc, clang]
        os:
        - ubuntu-latest
        # TODO
        # Can't exec "aclocal": No such file or directory
        # - macOS-latest

    steps:
    - uses: actions/checkout@v2

    - run: env
    - name: Fetch branches
      run: |
        git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        git fetch --unshallow
    - run: ./bootstrap
    - run: ./configure
    - run: make
    - run: make test-all

    - run: |
        git clean -d -x -f
        rm -fr tests/run-test-suite
        git worktree prune

    - name: Compiler version
      run: ${{ matrix.compiler }} --version
      env:
        CC: ${{ matrix.compiler }}
    - run: cmake .
      env:
        CC: ${{ matrix.compiler }}
    - run: make
      env:
        CC: ${{ matrix.compiler }}
    - run: make test
